### ISSUE TITLE
Tiny Typo in The DSC Book

### ISSUE THREAD

**Issue by GavinEke** [concentrateddon/TheDSCBookCode#1]
Hi Don,

Found a tiny typo top of page 53 under the heading 'Configuration Script Strategies'

> ...I only generated MOFs for NOD**E**1 and MACHINE3...

missing an E on the name NODE.

If there is a better place to submit small issues like this please let me know.
Regards,
Gavin

**Comment by majst32** [comment]
Will be fixed in next release.  Thanks!
